name: Update fass data files

on: 
  schedule: 
    - cron: '0 0 * * *' # Run this action everyday at 00:00

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      
      - name: checkout repo
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Change directory
        run: cd src/scrapers/fass-scraper

      - name: install dependencies
        run: | 
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Scrape fass
        run: python crawler.py 

      - name: Commit files
        run: | 
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "Fass data update" --allow-empty)

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: crawler-perf
            
